spring:
  application:
    name: website

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/it_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # dev only, prod -> validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: "anuradha123dk@gmail.com"
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    secret: ""

  cookie:
    secure: false     # true in production (HTTPS)
    same-site: Lax    # None if frontend & backend are on different domains

server:
  port: 8081
